### ISSUE TITLE
Do not add comment on header

### ISSUE THREAD

**Issue by Knack** [onesky/onesky-rails#11]
My opinion is that files downloaded using the gem should be identical to those downloaded manually via the web site.

In our team, some of us use the rake tasks but others still download files via the website. This makes the header comment to be added and deleted continuously in our Git version control:

<img width="960" alt="captura de pantalla 2015-09-09 a las 10 34 40" src="https://cloud.githubusercontent.com/assets/26083/9757115/c8d95ee2-56de-11e5-866d-4472a055c7a3.png">

At least it should be optional and configurable.

**Comment by VLMH** [comment]
Sorry that I missed the issue.
Let me think of a way to cater this. Thanks!
