### ISSUE TITLE
Update base language file

### ISSUE THREAD

**Issue by zedtux** [onesky/onesky-rails#13]
Given I have updated the base language texts, when I run `rake onesky:download` or `rake onesky:upload` it should also update the base language files.

**Comment by VLMH** [comment]
Do you mean that you will update base language strings at OneSky platform and you want to update base language files as well when perform `rake onesky:download`?

**Comment by zedtux** [comment]
Yes, that's right.

**Comment by zedtux** [comment]
Changing [this line](https://github.com/onesky/onesky-rails/blob/master/lib/onesky/rails/client.rb#L26) in order to always add do `@onesky_locales << locale` is doing the trick.

So I guess a new task `rake onesky:download_base` which is only downloading the base language only would be cool.

**Comment by qntn** [comment]
I tested the fork and it works well.

Is it possible to merge it in the near future ?

**Comment by VLMH** [comment]
Thank you so much!
Will merge it in a week.

**Comment by zedtux** [comment]
Thank you @VLMH :)

**Comment by qntn** [comment]
Thanks @VLMH
