### ISSUE TITLE
Issue with file names with one_sky:download

### ISSUE THREAD

**Issue by demental** [onesky/onesky-rails#2]
I started using onesky-rails in replacement of i18n-one_sky today, because as I removed the 'Default' from my translation source files, I encountered the error mentionned in this issue : https://github.com/onesky/i18n-one_sky-ruby/issues/8

So here I am. And for some reason (due to missing information in the api response suposately) Here is the output of the task onesky:download : 

```bash
demental$ rake onesky:download
onesky_en_GB/
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
  en-GB.yml
onesky_es_UY/
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
  es-UY.yml
onesky_pt_PT/
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
  pt-PT.yml
onesky_es_419/
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
  es-419.yml
```

As I suspected with this output, each downloaded translation file would replace the previous one, so while it should comply to the base locale file structure, it doesn't, and I can't properly download the translations.

I suggest one should name the downloaded files after the existing base file structure, and not after the API attachment response. I'll try to submit a PR within the end of the day to achieve this.

**Comment by jordigg** [comment]
Same issue here for me. Just switched and I only get 1 file per language with the lines of the last one. I'll try the fix submitted. Thanks @demental :+1:
