### ISSUE TITLE
This gem can only upload yml file?

### ISSUE THREAD

**Issue by zmcNotafraid** [onesky/onesky-rails#21]
I use it with gettext(fast_gettext) gem.
Their file load at Rails.root/locale/*  
Can I upload *.po file in {Rails.root}/locale

**Comment by maggieonesky** [comment]
Hi there,

The onesky-rails gem is only designed for uploading yml files. Please see [here](https://support.oneskyapp.com/hc/en-us/articles/206385418-Ruby-on-Rails-localization-support-YAML-YML-) for more information. But thank you for sharing the gem you used, our product team will consider this new feature :)
