### ISSUE TITLE
Onesky::Errors::BadRequestError: 400 Bad Request - Invalid source file when not found

### ISSUE THREAD

**Issue by zedtux** [onesky/onesky-rails#22]
As the gem is using the list of files on the disk, when running the `rake onesky:download_base` task, in case there is a new file on the local disk, it failles with a 400 Bas Request.

1. Update the OneSky API in order to return a 404 error instead of 400 (Here the request is well formed, so it cannot be a 400 error, but 404 Not Found)
2. When the 404 error occurs, warn in the console, but continue.

**Comment by maggieonesky** [comment]
Hi there, thank you for your message! Our product team will discuss changes to handling those errors. 

This is also an open source project, so feel free to add to the console logging :)

**Comment by zedtux** [comment]
Thank you @maggieonesky for your comment but why have you closed the issue? The second point is related to this gem, isn't it?

**Comment by davide1995** [comment]
After 4 years it's still 400 and I can't understand if my request is invalid or simply that the file name doesn't exists
