### ISSUE TITLE
Any plans on publishing 1.4.1 on RubyGems?

### ISSUE THREAD

**Issue by davidstosik** [onesky/onesky-rails#29]
**1.4.1** is described in the CHANGELOG (not as "future release"):
https://github.com/onesky/onesky-rails/commit/db09c0ba28e0cda6a690915d3d1a329f78927848

However, the last version of onesky-rails on RubyGems is **1.4.0**: https://rubygems.org/gems/onesky-rails

Are there any plans to fix that, or do I need to point to the GitHub repository in my Gemfile?

The fix that was added in 1.4.1 ([Upgrading the onesky-ruby dependancy gem](https://github.com/onesky/onesky-rails/pull/27)) helps resolve a gem version lock conflict, and will allow our project to upgrade the rest-client gem and support recent versions of other gems that use it.

**Comment by rubyluk** [comment]
:+1:
