### ISSUE TITLE
onesky.yml is not ERB enabled

### ISSUE THREAD

**Issue by demental** [onesky/onesky-rails#3]
While the i18n_one-sky gem the one_sky.yml is parsed through ERB, this is not the case with onesky-rails, which leads (in my case but I guess I'm not the only one) to a sensitive data issue. 
As I use figaro to keep sensitive values centralized, I would like to do the same with the one sky gem, and embed ERB tags in the onesky.yml. 

Unless ERB parsing was removed for a reason ? Please let me know. Anyway I'd like to submit a PR for this.

**Comment by VLMH** [comment]
Thanks! There's no reason not to parse file with ERB. Will review and merge the request for others.
