### ISSUE TITLE
Doesn't work on Rails 4.2

### ISSUE THREAD

**Issue by jordigg** [onesky/onesky-rails#7]
Gem doesn't work on rails 4.2 because dependencies.

onesky-rails (>= 0) ruby depends on
      onesky-ruby (~> 1.0.0) ruby depends on
        rest-client (~> 1.7.2) ruby

Where rails 4.2 uses rest-client 1.8.0

**Comment by VLMH** [comment]
Oops...thanks for your information
Will release a new version to upgrade rest-client soon

**Comment by jordigg** [comment]
I have submitted a pull request for onesky-ruby that makes it work with rails 4.2
Thanks!

**Comment by VLMH** [comment]
Fixed
